### ISSUE TITLE
There are no tests

### ISSUE THREAD

**Issue by larribas** [schoolhouse-io/colmena-realworld-example-app#1]
We need to automate tests against the realworld spec

**Comment by hecrj** [comment]
We could maybe use [this Postman collection](https://github.com/gothinkster/realworld/blob/master/api/Conduit.postman_collection.json) with[`newman`](https://www.getpostman.com/docs/v6/api_testing_and_collection_runner/newman_intro) as integration tests.

**Comment by hecrj** [comment]
There is a `run-api-tests.sh` here: https://github.com/gothinkster/realworld/blob/master/api/run-api-tests.sh
