### ISSUE TITLE
Decide how we'll implement the article feed

### ISSUE THREAD

**Issue by larribas** [schoolhouse-io/colmena-realworld-example-app#27]
In the spec there's a [feed endpoint](https://github.com/gothinkster/realworld/tree/master/api#feed-articles) made up of articles written by people you follow.

Problem: The people you follow is not necessarily a small number.

I see two ways to go here:
1. We assume there is an actual limit (say, 500) to the people you can follow, and we use the 500 ids in a SQL query.
2. We materialize a feed per user via listeners. New article published? Let's push it into the feeds of all users. I heard this is how facebook does it.
3. We take a hybrid / heuristic approach. If a user follows `< LIMIT` people, we calculate it. Otherwise we materialize it.

Since the purpose of this example is to show how we would do it in a real scenario, I would actually consider just (2) or (3), but let me know what you think!

**Comment by hecrj** [comment]
I will go with (2). I do not see the benefits of (3) over (2), besides database storage, and it is a more complex solution.

**Comment by larribas** [comment]
Fair enough, go ahead ;)
